<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.1.1 (Python 3.9.13 on win32)" generated="20231013 23:07:03.594" rpa="false" schemaversion="4">
<suite id="s1" name="cartDemo" source="C:\Users\Mohan\PycharmProjects\pythonProject\AutomationDemo\cartDemo.robot">
<kw name="Open my browser" library="keyword" type="SETUP">
<kw name="Open Browser" library="SeleniumLibrary">
<arg>https://www.saucedemo.com</arg>
<arg>chrome</arg>
<doc>Opens a new browser instance to the optional ``url``.</doc>
<msg timestamp="20231013 23:07:05.652" level="INFO">Opening browser 'chrome' to base url 'https://www.saucedemo.com'.</msg>
<status status="PASS" starttime="20231013 23:07:05.652" endtime="20231013 23:07:33.044"/>
</kw>
<kw name="Maximize Browser Window" library="SeleniumLibrary">
<doc>Maximizes current browser window.</doc>
<status status="PASS" starttime="20231013 23:07:33.044" endtime="20231013 23:07:33.235"/>
</kw>
<status status="PASS" starttime="20231013 23:07:05.652" endtime="20231013 23:07:33.235"/>
</kw>
<test id="s1-t1" name="LoginTestwithExcel using" line="13">
<kw name="Valid Login">
<arg>${username}</arg>
<arg>${password}</arg>
<arg>${firstName}</arg>
<arg>${lastName}</arg>
<arg>${postalCode}</arg>
<msg timestamp="20231013 23:07:33.235" level="FAIL">Variable '${username}' not found.</msg>
<status status="FAIL" starttime="20231013 23:07:33.235" endtime="20231013 23:07:33.235"/>
</kw>
<status status="FAIL" starttime="20231013 23:07:33.235" endtime="20231013 23:07:33.235">Variable '${username}' not found.</status>
</test>
<kw name="close all browsers" library="keyword" type="TEARDOWN">
<kw name="Close Browser" library="SeleniumLibrary">
<doc>Closes the current browser.</doc>
<status status="PASS" starttime="20231013 23:07:33.235" endtime="20231013 23:07:35.779"/>
</kw>
<status status="PASS" starttime="20231013 23:07:33.235" endtime="20231013 23:07:35.779"/>
</kw>
<status status="FAIL" starttime="20231013 23:07:03.594" endtime="20231013 23:07:35.779"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="cartDemo">cartDemo</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20231013 23:07:05.636" level="ERROR">Error in file 'C:\Users\Mohan\PycharmProjects\pythonProject\AutomationDemo\cartDemo.robot' on line 4: Importing library 'DataDriver' failed: ModuleNotFoundError: No module named 'DataDriver'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Users\Mohan\PycharmProjects\pythonProject\venv\Scripts\robot.exe
  C:\Users\Mohan\AppData\Local\Programs\Python\Python39\python39.zip
  C:\Users\Mohan\AppData\Local\Programs\Python\Python39\DLLs
  C:\Users\Mohan\AppData\Local\Programs\Python\Python39\lib
  C:\Users\Mohan\AppData\Local\Programs\Python\Python39
  C:\Users\Mohan\PycharmProjects\pythonProject\venv
  C:\Users\Mohan\PycharmProjects\pythonProject\venv\lib\site-packages</msg>
</errors>
</robot>
